server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/heartmatch
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

jwt:
  secret: heartmatch_secret_key_2026_change_me
  expiration: 86400000   # 24 hours in ms

logging:
  level:
    org.springframework.security: DEBUG