server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://db.jxgfwfdipibfddvmrbyc.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: ApxiygZhSTsmhcO3
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

jwt:
  secret: heartmatch_secret_key_2026_change_me
  expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG